### ISSUE TITLE
Unable to send: this.sendNotification("HTTP_REQUEST", {key: OPEN_GARAGE_DOOR});

### ISSUE THREAD

**Issue by McNose** [cederstrom/MMM-HTTPRequest#1]
First of all thank you for that module.
Now I am able to control my smart home by using the magic mirror.

However I dont get the notifications to work. I try to sent them out of the module [MMM-Touch](https://github.com/gfischershaw/MMM-Touch).
I tried `this.sendNotification("HTTP_REQUEST", {key: OPEN_GARAGE_DOOR});
 `
But with no luck. Then i have just seen your example using MMM-Button. There the word "key" is missing. Instead you wrote "request".
I am pretty new in programming.
Hope you can help me out.

Thanks
Mr.Coffee

Just to be sure: i changed your url to mine. So that schould not be the problem.

**Comment by cederstrom** [comment]
Hello @McNose!

This looks like a bug in the documentation 😊 
According to this line https://github.com/cederstrom/MMM-HTTPRequest/blob/master/MMM-HTTPRequest.js#L49 the correct syntax for what you are tryingt o acheive should probably be
`this.sendNotification("HTTP_REQUEST", { request: "OPEN_GARAGE_DOOR" });`

Please try that and get back to me if it is working.

**Comment by McNose** [comment]
Awesome. Now it works.
Thank you.

However there is another issue right now. In the documentation you wrote: 
onSuccess: "An object which describes a notification to send when the request finishes with HTTP 200 OK."
I always get the notification "HTTP Status: 202."

There is no matter what. Even if I comment it out in the config.js or even when I let your example code insight. There is always that massage.
Do you have an idea about this?

Thanks again.

**Comment by cederstrom** [comment]
Hello again @McNose!

Great that it's working now 👍 

I took a look at your HTTP 202 problem and noticed that `onSuccess` was only called if the response was HTTP 200. I have fixed that in pull request #3 (https://github.com/cederstrom/MMM-HTTPRequest/pull/3/files).

Please do a git pull of the module on your MagicMirror and see if you get the correct notfication now :)
